services:
  # https://www.mongodb.com/resources/products/compatibilities/docker
  mongodb:
    image: mongo
    container_name: mongodb-nvn
    networks:
      - nvn-network
    volumes:
      - mongodb-nvn-data:/data/db
    restart: always
  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: reverse-proxy-nvn
    networks:
      - nvn-network
    ports:
      - "3001:8080"
  redis:
    image: redis
    container_name: redis-nvn
    ports: "6379"
    networks:
      - nvn-network
    restart: always
    volume:
      - redis-nvn-data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      # https://www.docker.com/blog/how-to-setup-your-local-node-js-development-environment-using-docker/
    env_file:
      - ./api/.env
    container_name: api-nvn
    networks:
      - nvn-network
networks:
  nvn-network:
    driver: bridge
volumes:
  mongodb-nvn-data:
  redis-nvn-data: