name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish_api:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        app: [api, nginx]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker ${{ matrix.app }}
      run: | 
        docker login --username nasc1mento --password ${{ secrets.GHCR_PAT }} ghcr.io
        docker build ./${{ matrix.app }} . --tag ghcr.io/nasc1mento/${{ matrix.app }}:latest
        docker push ghcr.io/nasc1mento/${{ matrix.app }}

        

