name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker login --username nasc1mento --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build . --tag ghcr.io/nasc1mento/nvn-api:latest
        docker push ghcr.io/nasc1mento/nvn-api

